AWSTemplateFormatVersion: 2010-09-09
Description: Data Infrastructure for the udacity capstone project
Parameters:
  resourcePrefix:
    Description: Prefix for all resources
    Type: String
    Default: udacity-capstone
  rawBucketName:
    Description: Name of the bucket to place the raw data in
    Type: String
    Default: raw-data
  stagingBucketName:
    Description: Name of the bucket to place the staging data in
    Type: String
    Default: staging-data

Resources:

  rawDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref resourcePrefix
          - !Ref rawBucketName

  stagingDataBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref resourcePrefix
          - !Ref stagingBucketName

  utilBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref resourcePrefix
          - util-bucket

  dataResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Join 
        - ''
        - - !Ref resourcePrefix
          - -data-resource-group
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
        Query:
          StackIdentifier: !Ref AWS::StackId

Outputs:
  rawBucketName:
    Value: !Ref rawDataBucket
  stagingBucketName:
    Value: !Ref stagingDataBucket
  utilBucketName:
    Value: !Ref utilBucket