AWSTemplateFormatVersion: 2010-09-09
Description: Storage Infrastructure for the udacity capstone project
Parameters:
  resourcePrefix:
    Description: Prefix for all resources
    Type: String
    Default: udacity-capstone
  databaseName:
    Description: The name of the DB used to store the data
    Type: String
    Default: udacitycapstone
    AllowedPattern: '([a-z]|[0-9]|)+' 
  masterUsername:
    Description: username for the master user account for the cluster
    Type: String
    Default: udacity
    AllowedPattern: '([a-z])([a-z]|[0-9])*'
    ConstraintDescription: must start with a-z and contain only a-z or 0-9.
  masterPassword:
    Description: password for the master user account for the cluster
    Type: String
    NoEcho: 'true'
    MinLength: '8'
    MaxLength: '64'
    AllowedPattern: >-
     ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?!._*[@/\\\"']).*$
    ConstraintDescription: >-
     Enter alphanumeric password for the master user. The password must contain 8 to 64 printable ASCII characters, excluding: /, ", \'', \ and @. It must contain one uppercase letter, one lowercase letter, and one number.
     

Resources:

  ################################################
  ########## IAM

  redshiftRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join 
        - '-'
        - - !Ref resourcePrefix
          - redhshift-cluster-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - redshift.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  
  ################################################
  ########## Networking

  redshiftSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !ImportValue 'projectVPC'
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref resourcePrefix
              - redshift-subnet

  redshiftSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Join 
        - ''
        - - !Ref resourcePrefix
          - -redshift-security-group
      VpcId: !ImportValue 'projectVPC'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0
          Description: 'Public access to the redshift cluster'  
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  redshiftClusterSubnetGroup:
    Type: 'AWS::Redshift::ClusterSubnetGroup'
    Properties:
      Description: Redshift Cluster subnet group
      SubnetIds: 
        - !Ref redshiftSubnet
      Tags:
        - Key: Name
          Value: "Primary Redshift Cluster Subnet group"
  
  ################################################
  ########## Redshift Cluster
  
  redshiftCluster:
    Type: 'AWS::Redshift::Cluster'
    Properties:
      ClusterType: "multi-node" # use "multi-node" for a multi-node cluster, "single-node" for single-node
      ClusterIdentifier: !Join 
        - '-'
        - - !Ref resourcePrefix
          - redshift-cluster
      NumberOfNodes: 2 # only needed if ClusterType == "multi-node"
      NodeType: "dc2.large"
      DBName: !Ref databaseName
      Port: 5439
      MasterUsername: !Ref masterUsername
      MasterUserPassword: !Ref masterPassword
      VpcSecurityGroupIds:
        - !Ref redshiftSecurityGroup
      AutomatedSnapshotRetentionPeriod: 0
      PubliclyAccessible: 'true'
      ClusterSubnetGroupName: !Ref redshiftClusterSubnetGroup
      IamRoles:
        - !GetAtt redshiftRole.Arn
      Tags:
        - Key: Name
          Value: !Join 
            - '-'
            - - !Ref resourcePrefix
              - redshift-cluster
        
  storageResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Join 
        - ''
        - - !Ref resourcePrefix
          - -storage-resource-group
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
        Query:
          StackIdentifier: !Ref AWS::StackId

Outputs:
  redshiftRoleArn:
    Value: !GetAtt redshiftRole.Arn
  redshiftClusterId:
    Value: !Ref redshiftCluster
  redshiftClusterPublicDNS:
    Value: !GetAtt redshiftCluster.Endpoint.Address
  redshiftClusterPublicPort:
    Value: !GetAtt redshiftCluster.Endpoint.Port
  cassandraKeyspaceName:
    Value: !Ref cassandraKeyspace